import { genTimeBlock } from 'react-native-timetable';

export default [
  {
    title: "Math",
    startDate: genTimeBlock("MON", 9),
    endDate: genTimeBlock("MON", 10, 50),
    location: "Classroom 403",
    professor: "Kim",
  },
  {
    title: "Math",
    startDate: genTimeBlock("WED", 9),
    endDate: genTimeBlock("WED", 10, 50),
    location: "Classroom 403",
    professor: "Kim",
  },
  {
    title: "Physics",
    startDate: genTimeBlock("MON", 11),
    endDate: genTimeBlock("MON", 11, 50),
    location: "Lab 404",
    professor: "Einstein",
  },
  {
    title: "Physics",
    startDate: genTimeBlock("WED", 11),
    endDate: genTimeBlock("WED", 11, 50),
    location: "Lab 404",
    professor: "Einstein",
  },
  {
    title: "Lunch",
    startDate: genTimeBlock("MON", 12),
    endDate: genTimeBlock("MON", 13),
    location: "Student Restaurant",
    professor: "",
  },
  {
    title: "Lunch",
    startDate: genTimeBlock("TUE", 12),
    endDate: genTimeBlock("TUE", 13),
    location: "Student Cafeteria",
    professor: "",
  },
  {
    title: "Lunch",
    startDate: genTimeBlock("WED", 12),
    endDate: genTimeBlock("WED", 13),
    location: "Student Cafeteria",
    professor: "",
  },
  {
    title: "Lunch",
    startDate: genTimeBlock("THU", 12),
    endDate: genTimeBlock("THU", 13),
    location: "Student Cafeteria",
    professor: "",
  },
  {
    title: "Lunch",
    startDate: genTimeBlock("FRI", 12),
    endDate: genTimeBlock("FRI", 13),
    location: "Student Restaurant",
    professor: "",
  },
  {
    title: "Mandarin",
    startDate: genTimeBlock("TUE", 9),
    endDate: genTimeBlock("TUE", 10, 50),
    location: "Language Center",
    professor: "Chen",
  },
  {
    title: "Japanese",
    startDate: genTimeBlock("FRI", 9),
    endDate: genTimeBlock("FRI", 10, 50),
    location: "Language Center",
    professor: "Nakamura",
  },
  {
    title: "Club Activity",
    startDate: genTimeBlock("THU", 9),
    endDate: genTimeBlock("THU", 10, 50),
    location: "Activity Center",
    professor: "",
  },
  {
    title: "Club Activity",
    startDate: genTimeBlock("FRI", 13, 30),
    endDate: genTimeBlock("FRI", 14, 50),
    location: "Activity Center",
    professor: "",
  },
  {
    title: "Volunteer",
    startDate: genTimeBlock("MON", 13, 30),
    endDate: genTimeBlock("MON", 14, 50),
    location: "Community Hospital",
    professor: "",
  },
  {
    title: "Volunteer",
    startDate: genTimeBlock("MON", 16),
    endDate: genTimeBlock("MON", 16, 50),
    location: "Community Hospital",
    professor: "",
  },
];